In [1]:
# !pip install readabs pandas matplotlib
import readabs as ra
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

In [2]:
try:
    from paths import RAW_DIR
except ImportError:
    RAW_DIR = Path("data/raw")

RAW_DIR.mkdir(parents=True, exist_ok=True)

In [3]:
CAT_NO = "6345.0" #WPI Cat

#Series Map of employmrnt rate
"""
series_map = {
    "A2603609J": "Quarter_index_Total_Ourly_Rate_Pay_trend",
    "A2713849C": "Quarter_index_Total_Ourly_Rate_Pay_adjusted",
    "A2603609J": "Quarter_index_Total_Ourly_Rate_Pay_Original"
}
"""
START_YEAR = "2000"

RAW_DIR = Path('Data/raw')

In [4]:
def download_wpi_data(cat_no, series_id, label):
    #############################################################
    # Input : Cat No, Series_id, and Label
    # Output : Return : Tuple(df Monthly, df quarterly), File on data/raw/ Directory
    ##############################################################

    
    print(f"\nProcessing {label}...")
    
    # Fetch data tuple with readabs
    df, meta = ra.read_abs_series(cat=cat_no, series_id=series_id)
    
    # Ensure it is a DataFrame and filter starting years
    if isinstance(df, pd.Series):
        df = df.to_frame(name='value')
    
    df_filtered = df[df.index >= START_YEAR].copy()
    
    # Process Monthly Data
    # Rename Index and Column to the label
    df_filtered_final = df_filtered.rename_axis('date').rename(columns={df.columns[0]: label})
    
    data_path = RAW_DIR / f"abs_{label}_.csv"
    df_filtered_final.to_csv(data_path)
    print(f"Saved: {data_path}")

    return df_filtered_final

In [5]:
Season_adj_wpi = download_wpi_data(CAT_NO, 'A2713849C', 'Quarter_index_Total_Ourly_Rate_Pay_adjusted')


print("Quarter_index_Total_Ourly_Rate_Pay_adjusted")
Season_adj_wpi.tail()

Processing Quarter_index_Total_Ourly_Rate_Pay_adjusted...
Saved: Data\raw\abs_Quarter_index_Total_Ourly_Rate_Pay_adjusted_.csv
Quarter_index_Total_Ourly_Rate_Pay_adjusted

        Quarter_index_Total_Ourly_Rate_Pay_adjusted
date
2024Q4                                        153.9
2025Q1                                        155.3
2025Q2                                        156.7
2025Q3                                        157.9
2025Q4                                        159.2

In [6]:
print("Percentage change (QtoQ Quarter_index_Total_Ourly_Rate_Pay_adjusted")
pc_qtoq_wpi = ra.percent_change(Season_adj_wpi, 1)
pc_qtoq_wpi

Percentage change (QtoQ Quarter_index_Total_Ourly_Rate_Pay_adjusted

        Quarter_index_Total_Ourly_Rate_Pay_adjusted
date
2000Q1                                          NaN
2000Q2                                     0.974930
2000Q3                                     0.827586
2000Q4                                     0.957592
2001Q1                                     0.948509
...                                             ...
2024Q4                                     0.719895
2025Q1                                     0.909682
2025Q2                                     0.901481
2025Q3                                     0.765795
2025Q4                                     0.823306

[104 rows x 1 columns]

In [7]:
pc_qtoq_wpi = pc_qtoq_wpi.rename_axis('date').rename(columns={pc_qtoq_wpi.columns[0]: 'QtoQ percent Change'})
    
data_path = RAW_DIR / f"abs_QtoQ percent Change_.csv"
pc_qtoq_wpi.to_csv(data_path)
print(f"Saved: {data_path}")

Saved: Data\raw\abs_QtoQ percent Change_.csv